# Generated by Django 4.2.6 on 2023-11-01 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=25)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_id",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Security",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("ticker", models.CharField(max_length=10, unique=True)),
                ("exchange", models.CharField(max_length=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("country", models.CharField(default="USA", max_length=3)),
                ("isin", models.CharField(default="", max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ticker", models.CharField(max_length=20, unique=True)),
                ("quantity", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=6, max_digits=12)),
                ("side", models.CharField(choices=[("B", "Buy"), ("S", "Sell")], max_length=1)),
                ("trade_date", models.DateField()),
                ("is_last_trade", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("comments", models.CharField(max_length=140)),
                (
                    "portfolio_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_id",
                        to="portfolio.portfolio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("close", models.DecimalField(decimal_places=6, max_digits=12)),
                (
                    "ticker_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="ticker_id", to="portfolio.security"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["date", "ticker_id"], name="idx_date_tickerid"),
                    models.Index(fields=["ticker_id", "date"], name="idx_tickerid_date"),
                ],
            },
        ),
    ]
